//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    public partial class BillDetail
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdBill { get; set; }
        public int Qty { get; set; }
        public decimal Total { get; set; }
        public virtual Product Product { get; set; }
    }
}
