//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            //this.BillDetails = new List<BillDetail>();
        }
    
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdCompany { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Total { get; set; }
        public string Step { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual List<BillDetail> BillDetails { get; set; }
    }
}
